### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by wwboyer** [wwboyer/potatocho#1]
### This is just an explicit to-do list of current issues with PotatOcho in no particular order:

- [x] Add support for keypad input
- - [ ] Rework keypad input so that it's *slightly* less janky and terrible
- [x] Use an actual rendering library instead of just printing out the screen array to the terminal
- [x] Figure out why the "Quirks" test gets stuck in an infinite loop (possibly due to lack of keypad support)

#### Additionally, there are a couple of code readability issues I might want to fix at some point:

- [x] Rename the `gp_registers` to `v_registers` so that they're named closer to how most Chip-8 documentation refers to them
- [x] Rename the functions for opcodes. To put it bluntly, they look like a jumble of random numbers and letters and are hard to parse
